application: emailmon
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- appstats: on
- deferred: on

inbound_services:
- mail
- warmup

libraries:
- name: jinja2
  version: "2.6"

- name: webapp2
  version: latest

handlers:
- url: /add_image
  script: main.app
  login: required

- url: .*
  script: main.app
